### ISSUE TITLE
Bug in class MarcXmlParser

### ISSUE THREAD

**Issue by neilstevens2005** [ksclarke/freelib-marc4j#16]
I have been getting the following stacktrace when parsing a Marc XML data in a webserver using Freelib Marc4J (when building freelib-marc4J from the current master branch):

```
org.marc4j.MarcException: Unable to parse input
        at org.marc4j.MarcXmlParser.parse(MarcXmlParser.java:89)
        at org.marc4j.MarcXmlParser.parse(MarcXmlParser.java:60)
        at org.marc4j.MarcXmlParserThread.run(MarcXmlParserThread.java:111)
Caused by: java.io.IOException: Stream closed
        at org.apache.catalina.connector.InputBuffer.readByte(InputBuffer.java:315)
        at org.apache.catalina.connector.CoyoteInputStream.read(CoyoteInputStream.java:105)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityManager$RewindableInputStream.read(XMLEntityManager.java:2899)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:674)
        at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:189)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:812)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
        at org.marc4j.MarcXmlParser.parse(MarcXmlParser.java:87)
        ... 2 more
```
		
This only occurs sometimes (maybe 1 in every 5 runs when running in Java 8 on Linux).  The problem does not occur when using earlier versions of Java  or when using Windows.   I have investigated this and discovered it is being caused by a bug in the class MarcXmlParserThread (in the freelib-marc4J library).  The problem is caused by the member variable "InputSource input" not being declared "volatile".  This variable needs to be declared volatile since it will always be set in a different thread (regardless of whether it is set during construction or by the setter), to the thread using it (The thread defined by MarcXmlParserThread).

The simple fix to solve this problem is to add the "volatile" keyword to the "input" member variable.  (I have rebuilt the library with this change and can confirm it fixes my problem)

An alternative nicer way to fix this would be to add the "final" keyword to the "input" member variable and remove the "setInputSource" method, forcing the input source to be set in the constructor.  However this would be a change to the interface of the library, which is something I assume you are trying to avoid?

The exact same problem exists with the "TransformerHandler th" member which should also be declared final or volatile.

I would be happy to make the change these member variables to volatile if you can temporarily give me write access to the repository?

**Comment by ksclarke** [comment]
Thanks for reporting the issue @neilstevens2005

Hmm, I'm not entirely against changing the interface of the library, though I am aware the library has been around for a long time (prior to my forking) and that doing so might cause problems for users of my fork. In this case, though, I wonder how many people are really using setInputSource. It doesn't seem unreasonable to me to tie the input source to the thread.

Then again, perhaps I should save a major version bump for a collection of changes that break the API. Perhaps the volatile change is the way to go for now if that does resolve the issue for you. Would you mind submitting a GitHub pull request from your repo to this one? I can merge that in to add the volatile addition. Thanks!

**Comment by ksclarke** [comment]
Thanks! Merged. I'll create a new issue for the API-breaking alternative option.
