### ISSUE TITLE
Bug: MARC21 binary file that contains UTF8 chars (tested on Hebrew chars) parsing ends with error.

### ISSUE THREAD

**Issue by ksclarke** [ksclarke/freelib-marc4j#2]
From upstream marc4j:

When trying to parse MARC21 binary file that contains UTF8 chars(Hebrew chars were used in testing), parsing ends with error (using MarcStreamReader):

org.marc4j.MarcException: expected field terminator at end of field
at org.marc4j.MarcStreamReader.parseRecord(MarcStreamReader.java:223)
at org.marc4j.MarcStreamReader.next(MarcStreamReader.java:135)
at org.marcRDF.MarcToRDF.main(MarcToRDF.java:64)
expected field terminator at end of field

When i replace Hebrew chars with the English one, parsing works as expected...
In my opinion the problem is that UTF8 chars can be 1 - 4 bytes long, but currently in parsing module the assumption is that each char is exactly 1 byte long.

**Comment by ksclarke** [comment]
Looks like an issue with the character set being set incorrectly in the leader. Permissive reader can be used to guess at the character set.
